/******************************************************************************/
/***                Generated by IBExpert 18/07/21 16:50:45                 ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR GEN_ABASTECIMENTOS_ID;

CREATE TABLE ABASTECIMENTOS (
    ID_ABASTECE       BIGINT NOT NULL,
    NR_BOMBA          VARCHAR(5) NOT NULL,
    NR_TANQUE         VARCHAR(5) NOT NULL,
    DATA_ABASTECE     DATE NOT NULL,
    QTDE              DECIMAL(9,4),
    PRECO_LITRO       DECIMAL(9,4),
    VALOR_ABASTECIDO  DECIMAL(9,4),
    ALIQUOTA          DECIMAL(5,2),
    IMPOSTO           DECIMAL(9,2),
    FORMA_PGTO        VARCHAR(15)
);




/******************************************************************************/
/***                              Primary keys                              ***/
/******************************************************************************/

ALTER TABLE ABASTECIMENTOS ADD CONSTRAINT PK_ABASTECE PRIMARY KEY (ID_ABASTECE);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: TRIGGER_ABASTECIMENTOS_BI */
CREATE OR ALTER TRIGGER TRIGGER_ABASTECIMENTOS_BI FOR ABASTECIMENTOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  if (NEW.ID_abastece is NULL) then NEW.ID_abastece = GEN_ID(GEN_abastecimentos_ID, 1);
END
^

SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/
