INSERT INTO TANQUES (ID_TANQUE, NR_TANQUE, COMBUSTIVEL, PRECO)
             VALUES (1, '001', 'GASOLINA', 6.27);
INSERT INTO TANQUES (ID_TANQUE, NR_TANQUE, COMBUSTIVEL, PRECO)
             VALUES (2, '002', 'ÓLEO DIESEL', 4.5);
INSERT INTO TANQUES (ID_TANQUE, NR_TANQUE, COMBUSTIVEL, PRECO)
             VALUES (3, '003', 'ÁLCOOL', 5.38);
			 
INSERT INTO BOMBAS (ID_BOMBA, NR_BOMBA, ID_TANQUE)
            VALUES (1, '001', 1);
INSERT INTO BOMBAS (ID_BOMBA, NR_BOMBA, ID_TANQUE)
            VALUES (2, '002', 1);
INSERT INTO BOMBAS (ID_BOMBA, NR_BOMBA, ID_TANQUE)
            VALUES (3, '003', 2);
INSERT INTO BOMBAS (ID_BOMBA, NR_BOMBA, ID_TANQUE)
            VALUES (4, '004', 2);
			
INSERT INTO FORMA_PGTO (ID_PGTO, NM_FORMAPGTO)
                VALUES (1, 'DINHEIRO');
INSERT INTO FORMA_PGTO (ID_PGTO, NM_FORMAPGTO)
                VALUES (2, 'CARTÃO CRÉDITO');
INSERT INTO FORMA_PGTO (ID_PGTO, NM_FORMAPGTO)
                VALUES (3, 'CARTÃO DÉBITO');
INSERT INTO FORMA_PGTO (ID_PGTO, NM_FORMAPGTO)
                VALUES (4, 'PIX');
INSERT INTO FORMA_PGTO (ID_PGTO, NM_FORMAPGTO)
                VALUES (5, 'TRANSFERÊNCIA');
INSERT INTO FORMA_PGTO (ID_PGTO, NM_FORMAPGTO)
                VALUES (6, 'TICKET');
INSERT INTO FORMA_PGTO (ID_PGTO, NM_FORMAPGTO)
                VALUES (7, 'PIC PAY');
INSERT INTO FORMA_PGTO (ID_PGTO, NM_FORMAPGTO)
                VALUES (8, 'AME');

COMMIT WORK;
